import { TextWriter } from '@yellicode/core';
import { Generator } from '@yellicode/templating';

Generator.generate({outputFile: './quickstart-output.txt'}, (writer: TextWriter) => {
    writer.writeLine(`File generated by Yellicode at ${new Date().toISOString()}`);
}); 